name: Test Pull request and release
on:
  pull_request:
    types:
      - opened  # De default from github
      - reopened  # De default from github
      - synchronize  # De default from github
      - labeled  # When a label has been added
  release:
    types:
      - prereleased
      - released

permissions: write-all

jobs:
  remove-label:
    name: Remove the label in case the actor is not in our organization
    runs-on: ubuntu-latest
    outputs:
      is_organization_member: ${{ steps.is_organization_member.outputs.result }}
    steps:
    - name: Check if organization member
      id: is_organization_member
      uses: jamessingleton/is-organization-member@1.0.1
      with:
      # organization: "${{ github.repository_owner }}"
        organization: "newrelic"
        username: "${{ github.triggering_actor }}"
        token: "${{ secrets.GITHUB_TOKEN }}"

    - name: debug information
      run: |
        cat <<EOT
        repository_owner: "${{ github.repository_owner }}"
        triggering_actor: "${{ github.triggering_actor }}"
        actor:            "${{ github.actor }}"
        EOT

    - name: Remove label in case the actor is not in the organization
      if: ${{ steps.is_organization_member.outputs.result == 'false' }}
      uses: actions-ecosystem/action-remove-labels@v1
      with:
        labels: allow-execution

  step-running-without-label:
    name: Run testing
    runs-on: ubuntu-latest
    needs: remove-label
    steps:
    - name: This should run always
      run: |
        echo make build test

    - name: This should run the e2e in case you are from inside the org
      run: |
        echo run the e2e
