name: Test Pull request and release
on:
  pull_request:
    types:
      - opened  # De default from github
      - reopened  # De default from github
      - synchronize  # De default from github
      - labeled  # When a label has been added
  release:
    types:
      - prereleased
      - released

env:
  ORGANIZATION: newrelic
  MEMBER: "${{ github.triggering_actor }}"

jobs:
  remove-label:
    name: Remove the label in case the actor is not in our org
    runs-on: ubuntu-latest
    steps:
    - name: Look for the actor's organizations
      run: |
        echo "https://api.github.com/orgs/$ORGANIZATION/members/$MEMBER"
        
        RESPONSE_CODE=$(curl -s -o /dev/null -w "%{http_code}"\
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          "https://api.github.com/orgs/$ORGANIZATION/members/$MEMBER")

        echo RESPONSE_CODE="$RESPONSE_CODE" > $GITHUB_ENV

        echo actor: ${{ github.actor }}
        echo triggering_actor: ${{ github.triggering_actor }}

    - run: echo $RESPONSE_CODE

      # 204 - Response if requester is an organization member and user is a member
      # 302 - Response if requester is not an organization member
      # 404 - Not Found if requester is an organization member and user is not a member
    - if: env.RESPONSE_CODE != '204'
      uses: actions-ecosystem/action-remove-labels@v1
      with:
        labels: allow-execution
