name: Test Pull request and release
on:
  pull_request:
    types:
      - opened  # De default from github
      - reopened  # De default from github
      - synchronize  # De default from github
      - labeled  # When a label has been added
  release:
    types:
      - prereleased
      - released

permissions: write-all

jobs:
  remove-label:
    name: Remove the label in case the actor is not in our org
    runs-on: ubuntu-latest
    steps:
    - name: Check if organization member
      id: is_organization_member
      uses: jamessingleton/is-organization-member@v1
      with:
      # organization: "${{ github.repository_owner }}"
        organization: "newrelic"
        username: "${{ github.triggering_actor }}"
        token: "${{ secrets.GITHUB_TOKEN }}"
    - name: Check if organization member
      id: is_organization_member_roobre
      uses: jamessingleton/is-organization-member@v1
      with:
      # organization: "${{ github.repository_owner }}"
        organization: "newrelic"
        username: "roobre"
        token: "${{ secrets.GITHUB_TOKEN }}"
    - name: Check if organization member
      id: is_organization_member_ghtester
      uses: jamessingleton/is-organization-member@v1
      with:
      # organization: "${{ github.repository_owner }}"
        organization: "newrelic"
        username: "kang-ghtester"
        token: "${{ secrets.GITHUB_TOKEN }}"

    - name: Run a few things
      run: |
        echo is_organization_member:          ${{ steps.is_organization_member.outputs.result }} 
        echo is_organization_member_roobre:   ${{ steps.is_organization_member_roobre.outputs.result }} 
        echo is_organization_member_ghtester: ${{ steps.is_organization_member_ghtester.outputs.result }} 

    #- if: steps.is_organization_member.outputs.result == false
    #  uses: actions-ecosystem/action-remove-labels@v1
    #  with:
    #    labels: allow-execution
